name: Build & upload toolchain
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: buildjet-32vcpu-ubuntu-latest
    steps:
      - name: Download scripts
        uses: actions/checkout@v6

      - name: Deploy builder
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_NAME: ${{ secrets.GIT_NAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GH_BUILD_REPO: proton-clang-build
          GH_REL_REPO: proton-12
        run: |
          ci/build_agent.sh
